/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eStoreSearch;

public class Electronic extends Product {

    private String maker = new String();

    String defaultMaker = null;

    /* * * * * * * * * * * * * CONSTRUCTORS * * * * * * * * * * * * * */
    

    
    public Electronic() {
        super();
        maker = "";
}

    public Electronic (String productID, String description, double price, int year, String maker) throws Exception{
        super(productID, description, price, year);
        this.setMaker(maker);
    }
    
    public Electronic(Electronic original) // copy constructor
    {
        super(original);
        maker = original.maker;
    }


/** 
 * @return String
 */
/* * * * * * * * * * * * * * GETTERS * * * * * * * * * * * * * * */

    public String getMaker(){
        return maker;
    }


/** 
 * @param maker
 * @return boolean
 */
/* * * * * * * * * * * * * * SETTERS * * * * * * * * * * * * * * */

public boolean setMaker(String maker){
    //field not required, any value/digits/length allowed... set regardless of what stored in maker
        this.maker = (maker);
        return true;
}
  

/** 
 * @return String
 */
/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

@Override
public String toString(){
    return (super.toString() 
           + "Maker:  " + maker + "\n");
}


/** 
 * @param other
 * @return boolean
 */
@Override
public boolean equals(Object other){
    if (other == null){
        return false;
    }
    else if (getClass() != other.getClass()) {
        return false;
    }
    else {
        Electronic otherElectronic = (Electronic)other;
        return (super.equals(otherElectronic) 
               &&  maker.equalsIgnoreCase(otherElectronic.getMaker()) );
    }
}


/** 
 * @param args
 */
/* * * * * * * * * * * * * * * MAIN * * * * * * * * * * * * * * * */
    public static void main(String[] args) {
        

  
    }
}
